backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "basic-page"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Website elements"
        name: "elements"
        widget: "list"
        required: false
        fields:
          - label: "Hero"
            name: "hero"
            widget: "list"
            fields:
              - {label: Image, name: heroimage, widget: "image"}
              - {label: Title, name: herotitle, widget: "string"}
              - {label: Description, name: herodescription, widget: "string"}
              - {label: Link, name: herolink, widget: "string", required: false}
          - label: "Text"
            name: "text"
            widget: "list"
            fields:
              - {label: Paragraph, name: paragraph, widget: "markdown"}
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            fields:
              - label: "Gallery item"
                name: "galleryitem"
                widget: "list"
                fields:
                  - {label: Image, name: src, widget: "image"}
                  - {label: Thumbnail, name: thumbnail, widget: "image"}
                  - {label: Title, name: caption, widget: "string"}
          - label: "Quote"
            name: "quote"
            widget: "list"
            fields:
              - {label: Quote, name: quotetitle, widget: "string"}
              - {label: Quote author, name: quoteauthor, widget: "string"}
          - label: "Custom HTML"
            name: "customhtml"
            widget: "list"
            fields:
              - {label: Custom HTML, name: customhtml, widget: "string"}

  - name: "menu"
    label: "Menu"
    folder: "src/pages/menu"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "menu"}
      - {label: "Menu Title", name: "title", widget: "string"}
      - {label: "Menu path", name: "menupath", widget: "string"}
  - name: "settings"
    label: "Site Settings"
    folder: "src/pages/settings"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "settings"}
      - {label: "Website name", name: "title", widget: "string", required: true}
      - {label: "Company address", name: "companyaddress", widget: "markdown", required: false}
      - label: "Social Links"
        name: "sociallinks"
        widget: "object"
        fields:
          - {label: "Facebook URL", name: "facebook", widget: "string", required: false}
          - {label: "Twitter URL", name: "twitter", widget: "string", required: false}
          - {label: "Instagram URL", name: "instagram", widget: "string", required: false}
          